# Generated by Django 5.2.4 on 2025-08-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillsharespace_app', '0003_alter_vote_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('question', 'Question'), ('answer', 'Answer')], max_length=10)),
                ('object_id', models.PositiveIntegerField()),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='related_answer',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='related_question',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='question',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='vote',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='question',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='answer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='question',
            name='skillshares_search__92f3ce_gin',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='content',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='is_accepted',
            new_name='is_approved',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='content',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='is_flagged',
            new_name='is_approved',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='flag_reason',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='is_flagged',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='score',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='question',
            name='flag_count',
        ),
        migrations.RemoveField(
            model_name='question',
            name='flag_reason',
        ),
        migrations.RemoveField(
            model_name='question',
            name='score',
        ),
        migrations.RemoveField(
            model_name='question',
            name='search_vector',
        ),
        migrations.RemoveField(
            model_name='question',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='question',
            name='views',
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
