# Generated by Django 5.2.4 on 2025-08-05 15:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillsharespace_app', '0004_flag_remove_comment_answer_remove_comment_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='is_approved',
            new_name='approved',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='is_approved',
            new_name='approved',
        ),
        migrations.AddField(
            model_name='flag',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='question',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='answer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='flag',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
