# Generated by Django 5.2.4 on 2025-08-07 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('skillsharespace_app', '0005_rename_is_approved_answer_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flag',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
